### ISSUE TITLE
external css

### ISSUE THREAD

**Issue by kururu-abdo** [kururu-abdo/tornado#3]
i tried to get css from external  file 
by using importStylesheet("/source/ext.css")
but the messsage appear in the console
**Jan 30, 2019 11:51:17 PM tornadofx.FXKt importStylesheet
WARNING: Unable to find stylesheet at /source/ex.css - check that the path is correct**

note: i make **source** folder as **source root**

@edvin

**Comment by edvin** [comment]
If you made `source` a source root, that would place ex.css directly in your classpath `/`, so you should do `importStylesheet("/ext.css")`. Confirm your actual placement of ext.css by looking in your build folder.

**Comment by kururu-abdo** [comment]
it works :)
thanks
